# Generated by Django 5.0.7 on 2024-08-02 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=10)),
                ("market_cap", models.DecimalField(decimal_places=2, max_digits=20)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume_24h", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "circulating_supply",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                ("max_supply", models.DecimalField(decimal_places=2, max_digits=20)),
                ("logo", models.URLField(blank=True, null=True)),
                (
                    "crypto_id",
                    models.CharField(default="unknown", max_length=100, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("sentiment_score", models.FloatField()),
                ("source", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "token",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sentiment_analysis.token",
                    ),
                ),
            ],
        ),
    ]
