# Generated by Django 5.0.7 on 2024-08-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment_analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BitcoinSentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("price", models.FloatField()),
                ("volume", models.FloatField()),
                ("score1", models.FloatField()),
                ("score2", models.FloatField()),
                ("score3", models.FloatField()),
                ("sum", models.FloatField()),
                ("mean", models.FloatField()),
                ("count", models.IntegerField()),
            ],
        ),
    ]
