# Generated by Django 5.0.6 on 2024-05-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentiment_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
