# Generated by Django 5.0.6 on 2024-06-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TokenAnalysis",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("symbol", models.CharField(max_length=50)),
                ("platform", models.CharField(blank=True, max_length=255, null=True)),
                ("blocktime", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("whitepaper", models.URLField(blank=True, null=True)),
                ("official_forum", models.URLField(blank=True, null=True)),
                ("announcement", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("telegram", models.URLField(blank=True, null=True)),
                ("reddit", models.URLField(blank=True, null=True)),
                ("sentiment_votes_up", models.IntegerField(blank=True, null=True)),
                ("sentiment_votes_down", models.IntegerField(blank=True, null=True)),
                ("facebook_likes", models.IntegerField(blank=True, null=True)),
                ("twitter_followers", models.IntegerField(blank=True, null=True)),
                ("reddit_subscribers", models.IntegerField(blank=True, null=True)),
                (
                    "telegram_channel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("forks", models.IntegerField(blank=True, null=True)),
                ("stars", models.IntegerField(blank=True, null=True)),
                ("subscribers", models.IntegerField(blank=True, null=True)),
                ("total_issues", models.IntegerField(blank=True, null=True)),
                ("market_cap", models.BigIntegerField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=20, null=True
                    ),
                ),
                ("volume_24h", models.BigIntegerField(blank=True, null=True)),
                ("circulating_supply", models.BigIntegerField(blank=True, null=True)),
                ("max_supply", models.BigIntegerField(blank=True, null=True)),
                ("logo", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
