# Generated by Django 5.1 on 2024-08-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FundingRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coin_name", models.CharField(max_length=100)),
                ("stablecoin", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=50, unique=True)),
                ("funding_rate", models.FloatField()),
                ("exchange", models.CharField(max_length=100)),
                ("sentiment_score", models.FloatField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
