# Generated by Django 5.0.6 on 2024-06-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("price", models.FloatField()),
                ("volume", models.FloatField()),
                ("is_anomaly", models.BooleanField()),
            ],
        ),
    ]
