# Generated by Django 5.0.7 on 2024-08-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_id", models.CharField(max_length=100, unique=True)),
                ("volatility", models.FloatField()),
                ("liquidity", models.FloatField()),
                ("anomaly_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_id", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField()),
                ("price", models.FloatField()),
                ("volume", models.FloatField()),
                ("is_anomaly", models.BooleanField()),
            ],
            options={
                "unique_together": {("crypto_id", "timestamp")},
            },
        ),
    ]
