# Generated by Django 5.0.6 on 2024-06-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anomaly_detection", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crypto_id", models.CharField(max_length=100, unique=True)),
                ("volatility", models.FloatField()),
                ("liquidity", models.FloatField()),
                ("anomaly_count", models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="anomaly",
            unique_together={("crypto_id", "timestamp")},
        ),
    ]
